ManagamentTaskUpdateTest
nicolasdeory/DP2-Project pull request #99
Opened 2021-05-17 09:43 UTC by pedalopon

2021-05-17 10:38 UTC, nicolasdeory requested changes
![image](https://user-images.githubusercontent.com/1417708/118475530-a6270e00-b70c-11eb-8dc1-d8cfc3033df9.png)

These tests seem to be failing. Also, negative scenarios should be tested.

2021-05-17 10:38 UTC, nicolasdeory commented on src/test/java/management/task/ManagementTaskUpdateTest.java
> +    public void listAndShow(final int recordIndex, final String title,final String workload,final String description,final String isPublic, final String start, final String finish,
Perhaps change the method name to something more descriptivee

2021-05-18 14:59 UTC, nicolasdeory commented
Tests still seem to be failing @pedalopon 

![image](https://user-images.githubusercontent.com/1417708/118674860-69394500-b7fa-11eb-8fdd-fff2689e6a55.png)
![image](https://user-images.githubusercontent.com/1417708/118674892-6dfdf900-b7fa-11eb-9935-f0539788a4cd.png)

2021-05-18 15:09 UTC, pedalopon commented
Positive test working fine for me. Also the negative test failing is right just is missing workload validation in workplan update.

2021-05-22 11:01 UTC, nicolasdeory commented
Tests are working now, merging

2021-05-22 11:01 UTC, merged